Update trading.yml

diff --git a/.github/workflows/trading.yml b/.github/workflows/trading.yml
--- a/.github/workflows/trading.yml
+++ b/.github/workflows/trading.yml
@@ -169,16 +169,6 @@ jobs:
 
           git fetch origin "${GITHUB_REF_NAME}"
 
-          git rebase "origin/${GITHUB_REF_NAME}" || {
-
-            echo "WARNING: Git rebase failed."
-
-            git rebase --abort || true
-
-            exit 1
-
-          }
-
           git add \
             data/nse_classification_checkpoint.json \
             data/nse_industry_classification.csv \
@@ -192,6 +182,17 @@ jobs:
 
             git commit \
               -m "Update NSE classification data"
+
+            git pull \
+              --rebase \
+              origin \
+              "${GITHUB_REF_NAME}" || {
+
+              echo "WARNING: Git pull --rebase failed."
+
+              exit 1
+
+            }
 
             git push \
               origin \
